
// Orders Service Message Patterns
export const ORDERS_PATTERNS = {
  ORDER_CREATE: 'orders/create-order',
  ORDER_ACCEPT: 'orders/accept',
  ORDER_COMPLETE: 'orders/complete',
  ORDER_UPDATE_STATUS: 'orders/update-status',
  ORDER_FIND_ALL: 'orders/find-all',
  ORDER_FIND_PATISSIERE: 'orders/patissiere/find-all',
  ORDER_FIND_ONE: 'orders/find-one',
  ORDER_REMOVE: 'orders/remove',
  ORDER_ITEM_CREATE: 'orders/order-item/create',
  ORDER_ITEM_FIND_ALL: 'orders/order-item/find-all',
  ORDER_ITEM_FIND_ONE: 'orders/order-item/find-one',
  ORDER_ITEM_UPDATE: 'orders/order-item/update',
  ORDER_ITEM_REMOVE: 'orders/order-item/remove',
  ESTIMATION_CLIENT_CREATE: 'estimation/client',
  ESTIMATION_DELIVERY_CREATE: 'estimation/delivery',
  ESTIMATION_FIND_BY_ORDER: 'estimation/find-by-order',
  ESTIMATION_FIND_PENDING_CLIENT: 'estimation/find-pending-client',
  ESTIMATION_CONFIRM: 'estimation/confirm',
  ESTIMATION_FIND_ACCEPTED_DELIVERY: 'estimation/find-accepted-delivery',
  ESTIMATION_FIND_ESTIMATED_DELIVERY: 'estimation/find-estimated-delivery',
  ESTIMATION_MARK_PAID: 'estimation/mark-paid',
  ESTIMATION_FIND_ONE: 'estimation/find-one',
} as const;
